# constants for specifying initialization method
uint8 AUTO = 0
uint8 DIRECT = 1

# input pose for initialization
geometry_msgs/PoseWithCovarianceStamped[<=1] pose_with_covariance

# Variable to set initialization method
# AUTO: The initial position is automatically estimated with localization algorithm.
#       The input pose will be used as an initial guess if provided.
# DIRECT: The initial position is set directly by the input pose without going through localization algorithm.
uint8 method
---
# ERROR CODES used in response status in case of failure
uint16 ERROR_UNSAFE = 1
uint16 ERROR_GNSS_SUPPORT = 2
uint16 ERROR_GNSS = 3
uint16 ERROR_ESTIMATION = 4

autoware_common_msgs/ResponseStatus status
