# Area query for map loading.
# PCD grids that overlap with the area are going to be loaded (required)
AreaInfo area

---
# The timestamp when the data is generated or to be published (required)
std_msgs/Header header

# Newly loaded PCD maps with ID (required)
PointCloudMapCellWithID[] new_pointcloud_with_ids
